In [1]:
import pandas as pd

df= pd.read_csv(r'X:\Downloads\diabetes.csv')

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [2]:
df.shape

(768, 9)

In [3]:
X = df.drop(columns=['Outcome'])

X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [4]:
y = df['Outcome'].values
y[0:5]

array([1, 0, 1, 0, 1], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=1)
print("X_train share : {}".format(X_train.shape))
print("y_train share : {}".format(y_train.shape))
print("X_test share : {}".format(X_test.shape))
print("y_test share : {}".format(y_test.shape))

X_train share : (614, 8)
y_train share : (614,)
X_test share : (154, 8)
y_test share : (154,)


In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [9]:
knn.predict(X_test)[0:5]

array([1, 1, 0, 0, 1], dtype=int64)

In [10]:
knn.score(X_test, y_test)

0.7402597402597403

In [11]:
knn.predict(X_test)[0:20]

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0],
      dtype=int64)

In [12]:
knn.score(X_test, y_test)

0.7402597402597403

In [13]:
from sklearn.model_selection import cross_val_score
import numpy as np
knn_cv = KNeighborsClassifier(n_neighbors = 3)

cv_scores = cross_val_score(knn_cv, X, y, cv = 5)
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))

[0.68181818 0.69480519 0.75324675 0.75163399 0.68627451]
cv_scores mean:0.7135557253204311


In [17]:
from sklearn.model_selection import GridSearchCV

knn2 = KNeighborsClassifier()

param_grid = {"n_neighbors": np.arange(1,25)}

knn_gscv = GridSearchCV(knn2, param_grid, cv = 5)

knn_gscv.fit(X,y)

knn_gscv.best_params_

{'n_neighbors': 14}

In [18]:
knn_gscv.best_score_

0.7578558696205755